[CU-86bymbvd4] Map UI Sidebar
Eu-Open-Data/Frontend pull request #29
Opened 2024-05-14 20:34 UTC by BejenaruIoanMatei

Sidebarul contine butoanele (fara actiuni atribuite fiecarui buton in parte).

2024-05-14 20:34 UTC, sergane13 commented
Task linked: [CU-86bymbvd4 [FE-008] Map UI Sidebar](https://app.clickup.com/t/86bymbvd4)

2024-05-14 21:03 UTC, sergane13 requested changes
Please do the changes and get rid of merge conflicts erros.

2024-05-14 21:03 UTC, sergane13 commented on package.json
> +
blank space. Please remove.

2024-05-14 21:03 UTC, sergane13 commented on src/shared/App.jsx
Please add the sidebar together with components made by Gabriela.

2024-05-16 13:17 UTC, BogdanMihaica approved these changes

2024-05-16 13:42 UTC, sergane13 approved these changes
Looks fine to me.

2024-05-16 13:42 UTC, merged